CREATE DATABASE SneezePharma
GO

USE SneezePharma
GO

CREATE TABLE Clientes (
	id INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	Nome NVARCHAR(50) NOT NULL,
	CPF VARCHAR(11) NOT NULL UNIQUE,
	DataCadastro DATE NOT NULL,
	UltimaCompra DATETIME,
	StatusCliente BIT NOT NULL DEFAULT 1
);

CREATE TABLE ClientesRestritos (
	id INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	idCliente INT NOT NULL UNIQUE
);

CREATE TABLE Telefones (
	id INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	Tipo NVARCHAR(15) NOT NULL,
	DDD NUMERIC(2) NOT NULL,
	Numero NUMERIC(9) NOT NULL,
	idCliente INT NOT NULL
);

CREATE TABLE Vendas (
	id INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	DataVenda DATE NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	ValorTotal DECIMAL(5,2) NOT NULL
);

CREATE TABLE ItensVenda (
	id INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	idVenda INT NOT NULL,
	Medicamento VARCHAR(13) NOT NULL,
	Quantidade NUMERIC(3) NOT NULL,
	ValorUnitario NUMERIC(4,2) NOT NULL,
	TotalItem DECIMAL(5,2) NOT NULL
);

CREATE TABLE Medicamentos (
	CDB VARCHAR(13) PRIMARY KEY NOT NULL,
	Nome NVARCHAR(40) NOT NULL,
	Categoria CHAR NOT NULL,
	ValorVenda DECIMAL(4,2) NOT NULL,
	UltimaVenda DATETIME NOT NULL,
	DataCadastro DATE NOT NULL,
	Situacao BIT NOT NULL DEFAULT 1
);

CREATE TABLE Producoes (
	id INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	DataProducao DATE NOT NULL, 
	Medicamento VARCHAR(13) NOT NULL, 
	Quantidade NUMERIC(3) NOT NULL
);

CREATE TABLE ItensProducao (
	idProducao INT PRIMARY KEY NOT NULL,
	Principio VARCHAR(6) NOT NULL,
	QuantidadePrincipio NUMERIC(4) NOT NULL
);

CREATE TABLE Fornecedores (
	id INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	Cnpj VARCHAR(14) NOT NULL UNIQUE,
	RazaoSocial NVARCHAR(50) NOT NULL,
	Pais NVARCHAR(20),
	DataAbertura DATE NOT NULL,
	UltimoFornecimento DATETIME,
	DataCadastro DATE NOT NULL,
	Situacao BIT NOT NULL DEFAULT 1
);

CREATE TABLE FornecedoresRestritos (
	id INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	idFornecedor INT NOT NULL UNIQUE
);

CREATE TABLE PrincipiosAtivos (
	id INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	idPA AS ('AI' + RIGHT('0000' + CAST(id as VARCHAR(4)), 4)) PERSISTED,
	Nome NVARCHAR(20) NOT NULL,
	UltimaCompra DATETIME NOT NULL, 
	DataCadastro DATE NOT NULL,
	Situacao BIT NOT NULL DEFAULT 1
);

CREATE TABLE Compras (
	id INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	DateCompra DATE NOT NULL,
	Fornecedor VARCHAR(14) NOT NULL,
	ValorTotal DECIMAL(5, 2) NOT NULL
);

CREATE TABLE ItensCompra (
	id INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	idCompra INT NOT NULL,
	Ingrediente VARCHAR(6) NOT NULL,
	Quantidade NUMERIC(4) NOT NULL,
	ValorUnitario DECIMAL(3, 2) NOT NULL,
	TotalItem Decimal(5, 2) NOT NULL
);

ALTER TABLE PrincipiosAtivos
ADD CONSTRAINT UQ_PrincipiosAtivos UNIQUE (idPA);
