CREATE DATABASE SneezePharma;

USE SneezePharma;

CREATE TABLE Clientes (
	id INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	Nome NVARCHAR(40) NOT NULL,
	CPF VARCHAR(11) NOT NULL UNIQUE,
	DataCadastro DATE NOT NULL,
	UltimaCompra DATETIME,
	StatusCliente BIT NOT NULL DEFAULT 1
);

CREATE TABLE Telefones (
	id INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	Tipo NVARCHAR(10) NOT NULL,
	DDD NUMERIC(2) NOT NULL,
	Numero NUMERIC(9) NOT NULL
);

CREATE TABLE Vendas (
	id INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	DataVenda DATE NOT NULL,
	ValorTotal DECIMAL(5,2) NOT NULL,
	CPF VARCHAR(11) NOT NULL
);

CREATE TABLE ItensVenda (
	id INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	idVenda INT NOT NULL,
	Quantidade NUMERIC(3) NOT NULL,
	ValorUnitario NUMERIC(4,2) NOT NULL
);

